<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="KLS-00004.local" name="practitionerClinic.Protocol" tests="8" failures="0" timestamp="30 Apr 2016 02:29:01 GMT" time="121.632" errors="1">
  <testcase name="protocol_Status" time="12.085" classname="practitionerClinic.Protocol">
    <error type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertFalse(Assert.java:63)
	at org.testng.Assert.assertFalse(Assert.java:73)
	at com.kinduct.MavenFramework.SortTextPrac.sorttext(SortTextPrac.java:48)
	at practitionerClinic.Protocol.protocol_Status(Protocol.java:175)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
]]>
    </error>
  </testcase> <!-- protocol_Status -->
  <testcase name="protocol" time="18.879" classname="practitionerClinic.Protocol"/>
  <testcase name="protocol_Created" time="12.216" classname="practitionerClinic.Protocol"/>
  <testcase name="protocol_hide" time="13.571" classname="practitionerClinic.Protocol"/>
  <testcase name="protocol_BodyPart" time="13.837" classname="practitionerClinic.Protocol"/>
  <testcase name="protocol_copy" time="24.523" classname="practitionerClinic.Protocol"/>
  <testcase name="protocol_Tags" time="12.830" classname="practitionerClinic.Protocol"/>
  <testcase name="protocol_delete" time="13.691" classname="practitionerClinic.Protocol"/>
</testsuite> <!-- practitionerClinic.Protocol -->
